services:
  golang:
    container_name: "${COMPOSE_PROJECT_NAME}-golang"
    image: golang:1.22
    user: ${USER_ID}:${GROUP_ID}
    working_dir: /app
    environment:
      - GOCACHE=${GOCACHE}:${GOCACHE}:rw
    volumes:
      - "./:/app"
      - golang_cache:${GOCACHE}
      - ${GOPATH}:/go
    networks:
      default:
        ipv4_address: "${COMPOSE_PROJECT_NETWORK}.2"
    tty: true
    stdin_open: true

networks:
  default:
    name: "${COMPOSE_PROJECT_NAME}_default"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${COMPOSE_PROJECT_NETWORK}.0/24"
          gateway: "${COMPOSE_PROJECT_NETWORK}.1"

volumes:
  golang_cache:
    driver: local


