services:
  golang:
    container_name: "${COMPOSE_PROJECT_NAME}-golang"
    image: golang:1.22
    user: ${USER_ID}:${GROUP_ID}
    working_dir: /app
    environment:
      - GOCACHE=${GOCACHE}:${GOCACHE}:rw
    volumes:
      - "./:/app"
      - golang_cache:${GOCACHE}
      - ${GOPATH}:/go
    tty: true
    stdin_open: true

networks:
  default:
    name: "${COMPOSE_PROJECT_NAME}-default"
    driver: bridge
    ipam:
      driver: default

volumes:
  golang_cache:
    driver: local

